### ISSUE TITLE
Potential Dangerous Recursive Call within ReadLoop

### ISSUE THREAD

**Issue by Industry4** [multiplug-hub/MultiPlug.Ext.SerialPort#2]
Within `SerialPortComponent.cs` the function `ReadLoop()` is called within a task within a While loop. At the End of `ReadLoop()`, `ReadLoop()` is called again if there are bytes to Read.

- Firstly there seems to be no reason to call `ReadLoop()` again as the `ReadLoop()` is already in a While Loop.
- Secondly, this Recursive Call is potentially dangerous since the Read String will not be cleared and you could get a Stack Over Flow.

This extra call to `ReadLoop()` should be removed.

**Comment by multiplug-hub** [comment]
Code removed
